image: node:4

stages:
    # To include tests in next release
    # - test
    - package
    - publish
    - notify

# test:
#     tags:
#         - docker-executor
#     stage: test
#     except:
#         - triggers
#     script:
#         - npm install --registry ${NPM_REGISTRY}
#         - npm test

package:
    tags:
        - docker-executor
    stage: package
    only:
        - /^release-.*/
        - /^hf-.*/
    script:
        - npm run package -- --no-deps
    artifacts:
        name: ${CI_PROJECT_NAME}-${CI_BUILD_REF}
        paths:
            - dist/
            - doc/

publish:
    tags:
        - docker-executor
    stage: publish
    only:
        - master
    script:
        - npm install npm@latest -g --registry ${NPM_REGISTRY}
        - echo '//registry.npmjs.org/:_authToken="${NPM_TOKEN}"' > ./.npmrc
        - npm publish --access public --tag experimental

notify:
    tags:
        - docker-executor
    stage: notify
    except:
        - master
    script:
        - if [[ "$AUTO_NOTIFY" == true ]]; then
        -     echo 'Running notifyProjects.sh'
        -     ./build/notifyProjects.sh
        - else
        -     echo AUTO_NOTIFY is off, skipping notification.
        - fi
